/*
 * Cathy Qiu
 * June 22, 2018
 * Slot Machine (ICS 3UI game summative)
 */
package SlotMachine;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author cathy
 */
public class GameFrame extends javax.swing.JFrame {

    int coins1=20;
    int coins2=30;
    int coins3=50;
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
        fiveSlotsScreen.setVisible(false);
        fourSlotsScreen.setVisible(false);
        threeSlotsScreen.setVisible(false);
        welcomScreen.setVisible(true);
        
        setSize(400,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        threeSlotsButton = new javax.swing.JRadioButton();
        fourSlotsButton = new javax.swing.JRadioButton();
        fiveSlotsButton = new javax.swing.JRadioButton();
        goButton = new javax.swing.JButton();
        threeSlotsPanel = new javax.swing.JPanel();
        threeSlotsScreen = new javax.swing.JPanel();
        threeSlotsMoneyLabel = new javax.swing.JLabel();
        playThreeSlotsButton = new javax.swing.JButton();
        slot1Label = new javax.swing.JLabel();
        slot2Label = new javax.swing.JLabel();
        slot3Label = new javax.swing.JLabel();
        mainMenuButton = new javax.swing.JButton();
        fourSlotsScreen = new javax.swing.JPanel();
        slot1Label2 = new javax.swing.JLabel();
        slot2Label2 = new javax.swing.JLabel();
        slot3Label2 = new javax.swing.JLabel();
        slot4Label2 = new javax.swing.JLabel();
        playFourSlotsButton = new javax.swing.JButton();
        fourSlotsMoneyLabel = new javax.swing.JLabel();
        mainMenu2Button = new javax.swing.JButton();
        fiveSlotsScreen = new javax.swing.JPanel();
        slot1Label3 = new javax.swing.JLabel();
        slot2Label3 = new javax.swing.JLabel();
        slot3Label3 = new javax.swing.JLabel();
        slot4Label3 = new javax.swing.JLabel();
        slot5Label3 = new javax.swing.JLabel();
        playFiveSlotsButton = new javax.swing.JButton();
        fiveSlotsMoneyLabel = new javax.swing.JLabel();
        mainMenu3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomScreen.setMinimumSize(new java.awt.Dimension(420, 200));
        welcomScreen.setName(""); // NOI18N
        welcomScreen.setPreferredSize(new java.awt.Dimension(420, 200));
        welcomScreen.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome!");
        welcomScreen.add(jLabel1);
        jLabel1.setBounds(130, 50, 157, 26);

        jLabel2.setText("Select the number of slots:");
        welcomScreen.add(jLabel2);
        jLabel2.setBounds(20, 110, 129, 14);

        threeSlotsButton.setText("3");
        threeSlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeSlotsButtonActionPerformed(evt);
            }
        });
        welcomScreen.add(threeSlotsButton);
        threeSlotsButton.setBounds(270, 110, 31, 23);

        fourSlotsButton.setText("4");
        fourSlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourSlotsButtonActionPerformed(evt);
            }
        });
        welcomScreen.add(fourSlotsButton);
        fourSlotsButton.setBounds(320, 110, 31, 23);

        fiveSlotsButton.setText("5");
        fiveSlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveSlotsButtonActionPerformed(evt);
            }
        });
        welcomScreen.add(fiveSlotsButton);
        fiveSlotsButton.setBounds(370, 110, 31, 23);

        goButton.setText("Go!");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        welcomScreen.add(goButton);
        goButton.setBounds(180, 160, 49, 23);

        threeSlotsPanel.setMinimumSize(new java.awt.Dimension(420, 200));
        threeSlotsPanel.setPreferredSize(new java.awt.Dimension(420, 200));

        threeSlotsScreen.setPreferredSize(new java.awt.Dimension(420, 200));

        threeSlotsMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        threeSlotsMoneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        threeSlotsMoneyLabel.setText("$50");
        threeSlotsMoneyLabel.setMaximumSize(new java.awt.Dimension(100, 29));

        playThreeSlotsButton.setText("Play");
        playThreeSlotsButton.setMaximumSize(new java.awt.Dimension(100, 30));
        playThreeSlotsButton.setPreferredSize(new java.awt.Dimension(100, 75));
        playThreeSlotsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playThreeSlotsButtonMouseClicked(evt);
            }
        });

        slot1Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot1Label.setText("1");
        slot1Label.setToolTipText("");
        slot1Label.setPreferredSize(new java.awt.Dimension(100, 100));

        slot2Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot2Label.setText("1");
        slot2Label.setToolTipText("");
        slot2Label.setPreferredSize(new java.awt.Dimension(100, 100));

        slot3Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot3Label.setText("1");
        slot3Label.setToolTipText("");
        slot3Label.setPreferredSize(new java.awt.Dimension(100, 100));

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout threeSlotsScreenLayout = new javax.swing.GroupLayout(threeSlotsScreen);
        threeSlotsScreen.setLayout(threeSlotsScreenLayout);
        threeSlotsScreenLayout.setHorizontalGroup(
            threeSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threeSlotsScreenLayout.createSequentialGroup()
                .addComponent(mainMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(threeSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(threeSlotsScreenLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(threeSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threeSlotsScreenLayout.createSequentialGroup()
                        .addComponent(slot1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(slot2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(slot3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, threeSlotsScreenLayout.createSequentialGroup()
                        .addComponent(playThreeSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        threeSlotsScreenLayout.setVerticalGroup(
            threeSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threeSlotsScreenLayout.createSequentialGroup()
                .addGroup(threeSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threeSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(threeSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slot1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(playThreeSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        threeSlotsPanel.add(threeSlotsScreen);

        fourSlotsScreen.setMinimumSize(new java.awt.Dimension(420, 200));
        fourSlotsScreen.setPreferredSize(new java.awt.Dimension(420, 200));

        slot1Label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot1Label2.setText("1");
        slot1Label2.setToolTipText("");
        slot1Label2.setPreferredSize(new java.awt.Dimension(100, 100));

        slot2Label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot2Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot2Label2.setText("1");
        slot2Label2.setToolTipText("");
        slot2Label2.setPreferredSize(new java.awt.Dimension(100, 100));

        slot3Label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot3Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot3Label2.setText("1");
        slot3Label2.setToolTipText("");
        slot3Label2.setPreferredSize(new java.awt.Dimension(100, 100));

        slot4Label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot4Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot4Label2.setText("1");
        slot4Label2.setToolTipText("");
        slot4Label2.setPreferredSize(new java.awt.Dimension(100, 100));

        playFourSlotsButton.setText("Play");
        playFourSlotsButton.setMaximumSize(new java.awt.Dimension(100, 30));
        playFourSlotsButton.setPreferredSize(new java.awt.Dimension(100, 75));
        playFourSlotsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playFourSlotsButtonMouseClicked(evt);
            }
        });

        fourSlotsMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fourSlotsMoneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourSlotsMoneyLabel.setText("$100");
        fourSlotsMoneyLabel.setMaximumSize(new java.awt.Dimension(100, 29));

        mainMenu2Button.setText("Main Menu");
        mainMenu2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fourSlotsScreenLayout = new javax.swing.GroupLayout(fourSlotsScreen);
        fourSlotsScreen.setLayout(fourSlotsScreenLayout);
        fourSlotsScreenLayout.setHorizontalGroup(
            fourSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourSlotsScreenLayout.createSequentialGroup()
                .addComponent(mainMenu2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fourSlotsScreenLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(slot1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(slot2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(slot4Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(slot3Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(fourSlotsScreenLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(playFourSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fourSlotsScreenLayout.setVerticalGroup(
            fourSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourSlotsScreenLayout.createSequentialGroup()
                .addGroup(fourSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fourSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenu2Button))
                .addGap(37, 37, 37)
                .addGroup(fourSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slot1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot2Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot3Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot4Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(playFourSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fiveSlotsScreen.setMinimumSize(new java.awt.Dimension(420, 200));
        fiveSlotsScreen.setPreferredSize(new java.awt.Dimension(420, 200));

        slot1Label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot1Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot1Label3.setText("1");
        slot1Label3.setToolTipText("");
        slot1Label3.setPreferredSize(new java.awt.Dimension(100, 100));

        slot2Label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot2Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot2Label3.setText("1");
        slot2Label3.setToolTipText("");
        slot2Label3.setPreferredSize(new java.awt.Dimension(100, 100));

        slot3Label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot3Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot3Label3.setText("1");
        slot3Label3.setToolTipText("");
        slot3Label3.setPreferredSize(new java.awt.Dimension(100, 100));

        slot4Label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot4Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot4Label3.setText("1");
        slot4Label3.setToolTipText("");
        slot4Label3.setPreferredSize(new java.awt.Dimension(100, 100));

        slot5Label3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slot5Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot5Label3.setText("1");
        slot5Label3.setToolTipText("");
        slot5Label3.setPreferredSize(new java.awt.Dimension(100, 100));

        playFiveSlotsButton.setText("Play");
        playFiveSlotsButton.setMaximumSize(new java.awt.Dimension(100, 30));
        playFiveSlotsButton.setPreferredSize(new java.awt.Dimension(100, 75));
        playFiveSlotsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playFiveSlotsButtonMouseClicked(evt);
            }
        });

        fiveSlotsMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fiveSlotsMoneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiveSlotsMoneyLabel.setText("$150");
        fiveSlotsMoneyLabel.setMaximumSize(new java.awt.Dimension(100, 29));

        mainMenu3Button.setText("Main Menu");
        mainMenu3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fiveSlotsScreenLayout = new javax.swing.GroupLayout(fiveSlotsScreen);
        fiveSlotsScreen.setLayout(fiveSlotsScreenLayout);
        fiveSlotsScreenLayout.setHorizontalGroup(
            fiveSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fiveSlotsScreenLayout.createSequentialGroup()
                .addComponent(mainMenu3Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fiveSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fiveSlotsScreenLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(slot1Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slot2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slot4Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slot3Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(slot5Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fiveSlotsScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playFiveSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        fiveSlotsScreenLayout.setVerticalGroup(
            fiveSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fiveSlotsScreenLayout.createSequentialGroup()
                .addGroup(fiveSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiveSlotsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenu3Button))
                .addGap(41, 41, 41)
                .addGroup(fiveSlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slot1Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot2Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot3Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot4Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slot5Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(playFiveSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(threeSlotsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcomScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fourSlotsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fiveSlotsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threeSlotsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcomScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fourSlotsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fiveSlotsScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fourSlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourSlotsButtonActionPerformed
        welcomScreen.setVisible(false);
        fourSlotsScreen.setVisible(true);
    }//GEN-LAST:event_fourSlotsButtonActionPerformed

    private void threeSlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeSlotsButtonActionPerformed
        welcomScreen.setVisible(false);
        threeSlotsScreen.setVisible(true);
    }//GEN-LAST:event_threeSlotsButtonActionPerformed

    private void fiveSlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveSlotsButtonActionPerformed
        welcomScreen.setVisible(false);
        fiveSlotsScreen.setVisible(true);
    }//GEN-LAST:event_fiveSlotsButtonActionPerformed

    private void playThreeSlotsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playThreeSlotsButtonMouseClicked
        coins1-=1;
        int slot1 = (int) (Math.random()*5) + 1;
        int slot2 = (int) (Math.random()*5) + 1;
        int slot3 = (int) (Math.random()*5) + 1;
        
        slot1Label.setText(String.valueOf(slot1));
        slot2Label.setText(String.valueOf(slot2));
        slot3Label.setText(String.valueOf(slot3));
        
        
        if (slot1 == slot2 && slot2 == slot3) {
            
            switch (slot1) {
                case 1:
                    coins1+=5;
                    JOptionPane.showMessageDialog(this, "You win 5 coins! ");
                    break;
                case 2:
                    coins1+=10;
                    JOptionPane.showMessageDialog(this, "You win 10 coins! ");
                    break;
                case 3:
                    coins1+=15;
                    JOptionPane.showMessageDialog(this, "You win 15 coins! ");
                    break;
                default:
                    coins1+=slot1;
                    JOptionPane.showMessageDialog(this, "You win " + slot1 + " coins");
            }
        }
        threeSlotsMoneyLabel.setText("$" + String.valueOf(coins1));
        
        if(coins1==0) {
            int n=JOptionPane.showConfirmDialog(
            this,
                "Play again?",
                "Slot Machine",
                    JOptionPane.YES_NO_OPTION);
            
            if (n==0) {
                coins1=20;
                threeSlotsMoneyLabel.setText("$" + String.valueOf(coins1));
            }
            else
            {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_playThreeSlotsButtonMouseClicked

    private void playFourSlotsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playFourSlotsButtonMouseClicked
        coins2-=1;
        int slot1 = (int) (Math.random()*4) + 1;
        int slot2 = (int) (Math.random()*4) + 1;
        int slot3 = (int) (Math.random()*4) + 1;
        int slot4 = (int) (Math.random()*4) + 1;
        
        slot1Label2.setText(String.valueOf(slot1));
        slot2Label2.setText(String.valueOf(slot2));
        slot3Label2.setText(String.valueOf(slot3));
        slot4Label2.setText(String.valueOf(slot4));        
        
        if (slot1 == slot2 && slot2 == slot3) {
            if  (slot3 == slot4) {
                    
            switch (slot1) {
                case 1:
                    coins2+=15;
                    JOptionPane.showMessageDialog(this, "You win 15 coins! ");
                    break;
                case 2:
                    coins2+=30;
                    JOptionPane.showMessageDialog(this, "You win 30 coins! ");
                    break;
                case 3:
                    coins2+=20;
                    JOptionPane.showMessageDialog(this, "You win 20 coins! ");
                    break;
                default:
                    coins2+=slot1;
                    JOptionPane.showMessageDialog(this, "You win " + slot1 + " coins");
            }
            }
        }
        fourSlotsMoneyLabel.setText("$" + String.valueOf(coins2));
        
        if(coins2==0) {
            int n=JOptionPane.showConfirmDialog(
            this,
                "Play again?",
                "Slot Machine",
                    JOptionPane.YES_NO_OPTION);
            
            if (n==0) {
                coins2=30;
                fourSlotsMoneyLabel.setText("$" + String.valueOf(coins2));
            }
            else
            {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_playFourSlotsButtonMouseClicked

    private void mainMenu2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu2ButtonActionPerformed
        fiveSlotsScreen.setVisible(false);
        fourSlotsScreen.setVisible(false);
        threeSlotsScreen.setVisible(false);
        welcomScreen.setVisible(true);
    }//GEN-LAST:event_mainMenu2ButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        fiveSlotsScreen.setVisible(false);
        fourSlotsScreen.setVisible(false);
        threeSlotsScreen.setVisible(false);
        welcomScreen.setVisible(true);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void playFiveSlotsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playFiveSlotsButtonMouseClicked
        coins3-=1;
        int slot1 = (int) (Math.random()*4) + 1;
        int slot2 = (int) (Math.random()*4) + 1;
        int slot3 = (int) (Math.random()*4) + 1;
        int slot4 = (int) (Math.random()*4) + 1;
        int slot5 = (int) (Math.random()*4) + 1;
        
        slot1Label3.setText(String.valueOf(slot1));
        slot2Label3.setText(String.valueOf(slot2));
        slot3Label3.setText(String.valueOf(slot3));
        slot4Label3.setText(String.valueOf(slot4));        
        slot5Label3.setText(String.valueOf(slot5));        

        if (slot1 == slot2 && slot2 == slot3) {
            if (slot3 == slot4 && slot4 == slot5){
            
            switch (slot1) {
                case 1:
                    coins3+=15;
                    JOptionPane.showMessageDialog(this, "You win 15 coins! ");
                    break;
                case 2:
                    coins3+=30;
                    JOptionPane.showMessageDialog(this, "You win 30 coins! ");
                    break;
                case 3:
                    coins3+=20;
                    JOptionPane.showMessageDialog(this, "You win 20 coins! ");
                    break;
                default:
                    coins3+=slot1;
                    JOptionPane.showMessageDialog(this, "You win " + slot1 + " coins");
            }
        }
        fiveSlotsMoneyLabel.setText("$" + String.valueOf(coins3));
        
        if(coins3==0) {
            int n=JOptionPane.showConfirmDialog(
            this,
                "Play again?",
                "Slot Machine",
                    JOptionPane.YES_NO_OPTION);
            
            if (n==0) {
                coins3=50;
                fiveSlotsMoneyLabel.setText("$" + String.valueOf(coins3));
            }
            else
            {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_playFiveSlotsButtonMouseClicked
    }
    
    private void mainMenu3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu3ButtonActionPerformed
        fiveSlotsScreen.setVisible(false);
        fourSlotsScreen.setVisible(false);
        threeSlotsScreen.setVisible(false);
        welcomScreen.setVisible(true);
    }//GEN-LAST:event_mainMenu3ButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if (threeSlotsButton.isSelected()) {
            welcomScreen.setVisible(false);
            fourSlotsScreen.setVisible(false);
            fiveSlotsScreen.setVisible(false);
            threeSlotsScreen.setVisible(true);
        } else if (fourSlotsButton.isSelected()) {
            welcomScreen.setVisible(false);
            fourSlotsScreen.setVisible(true);
            threeSlotsScreen.setVisible(false);
            fiveSlotsScreen.setVisible(false);
        } else if (fiveSlotsButton.isSelected()) {
            welcomScreen.setVisible(false);
            fourSlotsScreen.setVisible(false);
            threeSlotsScreen.setVisible(false);
            fiveSlotsScreen.setVisible(true);    
        }
    }//GEN-LAST:event_goButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//set everything to blank

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton fiveSlotsButton;
    private javax.swing.JLabel fiveSlotsMoneyLabel;
    private javax.swing.JPanel fiveSlotsScreen;
    private javax.swing.JRadioButton fourSlotsButton;
    private javax.swing.JLabel fourSlotsMoneyLabel;
    private javax.swing.JPanel fourSlotsScreen;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mainMenu2Button;
    private javax.swing.JButton mainMenu3Button;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton playFiveSlotsButton;
    private javax.swing.JButton playFourSlotsButton;
    private javax.swing.JButton playThreeSlotsButton;
    private javax.swing.JLabel slot1Label;
    private javax.swing.JLabel slot1Label2;
    private javax.swing.JLabel slot1Label3;
    private javax.swing.JLabel slot2Label;
    private javax.swing.JLabel slot2Label2;
    private javax.swing.JLabel slot2Label3;
    private javax.swing.JLabel slot3Label;
    private javax.swing.JLabel slot3Label2;
    private javax.swing.JLabel slot3Label3;
    private javax.swing.JLabel slot4Label2;
    private javax.swing.JLabel slot4Label3;
    private javax.swing.JLabel slot5Label3;
    private javax.swing.JRadioButton threeSlotsButton;
    private javax.swing.JLabel threeSlotsMoneyLabel;
    private javax.swing.JPanel threeSlotsPanel;
    private javax.swing.JPanel threeSlotsScreen;
    private javax.swing.JPanel welcomScreen;
    // End of variables declaration//GEN-END:variables

}



    int z=0;
    Icon a=new ImageIcon("C:\\Users\\cathy\\Downloads\\SlotMachine\\Artboard 1");
    Icon b=new ImageIcon("C:\\Users\\cathy\\Downloads\\SlotMachine\\Artboard 2");
    Icon c=new ImageIcon("C:\\Users\\cathy\\Downloads\\SlotMachine\\Artboard 3");
    Timer T=new Timer(100, new ActionListener()
    {public void actionPerformed(ActionEvent e)
    {
        z++;
        switch(z)
        {
            case 1:
            {
                jLabel5.setIcon(a);
                break;
            }
            case 2:
            {
                jLabel6.setIcon(b);
                break;
            }
            case 3:
            {
                jLabel7.setIcon(c);
                break;
            }
        }
        if (z==3)
        {
            z=0;
        }
    }

    });
